
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-07-13T09:58:32-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "562ed04dcc508263541a5f94fe090ef8efc1372e",
 "version": "2021.07.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
